# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
# - task: octane-test-runner-start-task@1
#   inputs:
#     OctaneServiceConnection: 'connectionOctane'
#     WorkspaceList: '1002'
#     Framework: junit

- task: octane-start-task@2
  inputs:
    OctaneServiceConnection: 'connectionOctane'
    WorkspaceList: '1002'
    CreatePipelineCheckbox: true

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  continueOnError: true

# - script: |
#     mvn com.microfocus.adm.almoctane.bdd:bdd2octane:run -DreportFiles="**/results/tests/*.xml" -DfeatureFiles="**/results/features/*.feature" -Dframework="cucumber-jvm" -DresultFile="converted-test-results.xml"
#   displayName: 'Convert Test Results'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(System.DefaultWorkingDirectory)/converted-test-results.xml'
#     artifact: 'bdd2octaneResults'
#     publishLocation: 'pipeline'

# - task: DownloadPipelineArtifact@2
#   inputs:
#     artifact: 'bdd2octaneResults'
#     path: '$(System.DefaultWorkingDirectory)/results'

- task: octane-end-task@2
  inputs:
    OctaneServiceConnection: 'connectionOctane'
#    CucumberReportPath: '$(System.DefaultWorkingDirectory)/results'
    WorkspaceList: '1002'