# azure-pipelines.yml

trigger:
- master

parameters:
  - name: mavenGoals
    type: string
    default: clean test
    values:
      - clean test
      - not clean test
  - name: octane_auto_action_execution_id
    type: string
    default: 'value'

pool: Default

steps:
# Expose parameters as runtime variables

- task: octane-start-task-private@1
  inputs:
    OctaneServiceConnection: 'azurePConnection'
    WorkspaceList: '7003'
    CreatePipelineCheckbox: true

- script: |
    echo "Hello!"
    echo "This is a regular script step."
    echo "Parameter value for mavenGoals: ${{ parameters.mavenGoals }}"
  displayName: 'Say Hello'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: '${{ parameters.mavenGoals }}'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  continueOnError: true

# Optional step based on parameter

- task: octane-end-task-private@1
  inputs:
    OctaneServiceConnection: 'azurePConnection'
    WorkspaceList: '7003'
    Framework: 'junit'