# azure-pipelines.yml

trigger:
- master

parameters:
  - name: mavenGoals
    type: string
    default: clean test
    values:
      - clean test
      - not clean test

pool: Default

steps:
# Expose parameters as runtime variables

- task: octane-start-task-private@1
  condition: always()
  inputs:
    OctaneServiceConnection: 'octaneConnectionPrivate'
    WorkspaceList: '2001'
    CreatePipelineCheckbox: true

- script: |
    echo "Hello, $(name)!"
    echo "This is a regular script step."
    echo "Parameter value for mavenGoals: $(param_mavenGoals)"
  displayName: 'Say Hello'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: '${ parameters.mavenGoals }'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  continueOnError: true

# Optional step based on parameter

- task: octane-end-task-private@1
  condition: always()
  inputs:
    OctaneServiceConnection: 'octaneConnectionPrivate'
    WorkspaceList: '2001'
